# Generated by Django 5.2.17 on 2026-09-06 10:13

import cloudinary.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('region', models.CharField(choices=[('addis_ababa', 'Addis Ababa'), ('lalibela', 'Lalibela'), ('simien', 'Simien Mountains'), ('omo_valley', 'Omo Valley'), ('danakil', 'Danakil Depression'), ('axum', 'Axum'), ('gondar', 'Gondar'), ('harar', 'Harar'), ('custom', 'Custom/Multi-Region')], db_index=True, max_length=50)),
                ('short_description', models.CharField(help_text='Brief summary for list views and SEO', max_length=250)),
                ('description', models.TextField(help_text='Full detailed itinerary')),
                ('itinerary', models.TextField(blank=True, help_text='Day-by-day itinerary')),
                ('hero_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('image_2', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('image_3', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('price_per_person', models.DecimalField(decimal_places=2, help_text='Price in ETB', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('duration_days', models.IntegerField(help_text='Total duration in days', validators=[django.core.validators.MinValueValidator(1)])),
                ('max_group_size', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('challenging', 'Challenging'), ('strenuous', 'Strenuous')], default='moderate', max_length=20)),
                ('includes', models.TextField(blank=True, help_text="What's included (transport, meals, guide, etc.)")),
                ('excludes', models.TextField(blank=True, help_text="What's not included")),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('views', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Tour Package',
                'verbose_name_plural': 'Tour Packages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug', 'is_active'], name='tours_tour_slug_d43e72_idx'), models.Index(fields=['region', 'is_active'], name='tours_tour_region_45146a_idx'), models.Index(fields=['is_featured', 'is_active'], name='tours_tour_is_feat_c290e0_idx')],
            },
        ),
        migrations.CreateModel(
            name='TourImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('alt_text', models.CharField(blank=True, max_length=100)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tours.tour')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_nationality', models.CharField(blank=True, max_length=100)),
                ('tour_date', models.DateField()),
                ('number_of_guests', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('special_requests', models.TextField(blank=True)),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('telebirr', 'Telebirr'), ('chapa', 'Chapa (Card/Mobile)'), ('cash', 'Cash on Arrival')], default='bank_transfer', max_length=20)),
                ('payment_slip', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('payment_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending Inquiry'), ('confirmed', 'Confirmed'), ('paid', 'Paid'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('reference_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tours.tour')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer_email'], name='tours_booki_custome_0af672_idx'), models.Index(fields=['status', '-created_at'], name='tours_booki_status_6011e8_idx'), models.Index(fields=['tour_date'], name='tours_booki_tour_da_ee37a1_idx')],
            },
        ),
    ]
