# Generated by Django 5.2.17 on 2026-09-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_slip',
            field=models.ImageField(blank=True, null=True, upload_to='bookings/payment_slips/'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='tours/heroes/'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='tours/additional/'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='tours/additional/'),
        ),
        migrations.AlterField(
            model_name='tourimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tours/gallery/'),
        ),
    ]
